development:
  adapter: postgresql
  encoding: unicode
  database: singlelinkme_dev
  pool: 5
  username: cmakoumbou
  password: mabika

test:
  adapter: postgresql
  encoding: unicode
  database: singlelinkme_test
  pool: 5
  username: cmakoumbou
  password: mabika